/*
 * Timing.h
 *
 * Created: 3/23/2021 10:44:36 AM
 *  Author: hanle
 */ 
//This File Will include needed declarations and functions to use the RTC to make a delay us function
#ifndef TIMING_H_
#define TIMING_H_
void changeClock(){
	NVMCTRL->CTRLB.bit.RWS = 1;
	SYSCTRL->XOSC32K.reg =SYSCTRL_XOSC32K_STARTUP(0x7) |SYSCTRL_XOSC32K_EN32K |SYSCTRL_XOSC32K_XTALEN;
	SYSCTRL->XOSC32K.bit.ENABLE = 1;
	while(!SYSCTRL->PCLKSR.bit.XOSC32KRDY);
	
	GCLK->GENDIV.reg =GCLK_GENDIV_ID(1) |GCLK_GENDIV_DIV(1);
	GCLK->GENCTRL.reg =
	GCLK_GENCTRL_ID(1) |GCLK_GENCTRL_SRC_XOSC32K |GCLK_GENCTRL_IDC |GCLK_GENCTRL_GENEN;
	while(GCLK->STATUS.bit.SYNCBUSY);
	
	GCLK->CLKCTRL.reg =GCLK_CLKCTRL_ID_DFLL48 |GCLK_CLKCTRL_GEN_GCLK1 |GCLK_CLKCTRL_CLKEN;
	
	while(!SYSCTRL->PCLKSR.bit.DFLLRDY);
	SYSCTRL->DFLLCTRL.reg = SYSCTRL_DFLLCTRL_ENABLE;
	while(!SYSCTRL->PCLKSR.bit.DFLLRDY);


	SYSCTRL->DFLLMUL.reg =SYSCTRL_DFLLMUL_MUL(1465) |SYSCTRL_DFLLMUL_FSTEP(511) |SYSCTRL_DFLLMUL_CSTEP(31);
	while(!SYSCTRL->PCLKSR.bit.DFLLRDY);
	
	uint32_t coarse = (*((uint32_t *)FUSES_DFLL48M_COARSE_CAL_ADDR) & FUSES_DFLL48M_COARSE_CAL_Msk) >> FUSES_DFLL48M_COARSE_CAL_Pos;
	SYSCTRL->DFLLVAL.bit.COARSE = coarse;
	while(!SYSCTRL->PCLKSR.bit.DFLLRDY);
	
	SYSCTRL->DFLLCTRL.reg |=SYSCTRL_DFLLCTRL_MODE |SYSCTRL_DFLLCTRL_WAITLOCK |SYSCTRL_DFLLCTRL_ENABLE;
	while (!SYSCTRL->PCLKSR.bit.DFLLLCKC || !SYSCTRL->PCLKSR.bit.DFLLLCKF) {}
		
	GCLK->GENCTRL.reg =GCLK_GENCTRL_ID(0) |GCLK_GENCTRL_SRC_DFLL48M |GCLK_GENCTRL_IDC |GCLK_GENCTRL_GENEN;
	while(GCLK->STATUS.bit.SYNCBUSY);
}
void initRTC(){
	//A generic clock (GCLK_RTC) is required to clock the RTC. This clock must be configured and enabled in the Generic Clock Controller before using the RTC(Gen Clock ID 4, and )
	
	GCLK->GENDIV.reg  = GCLK_GENDIV_ID(0)|GCLK_GENDIV_DIV(0);
	GCLK->CLKCTRL.reg = GCLK_CLKCTRL_ID_RTC | GCLK_CLKCTRL_CLKEN | GCLK_CLKCTRL_GEN(0);
	
	/*GCLK->GENCTRL.reg = GCLK_GENCTRL_ID(4)|  GCLK_GENCTRL_GENEN;
	GCLK->CLKCTRL.reg = GCLK_CLKCTRL_ID_RTC |GCLK_CLKCTRL_GEN_GCLK4|GCLK_CLKCTRL_CLKEN; */
	PM->APBAMASK.reg |= PM_APBAMASK_RTC;
	//Setting Settings for RTC*/

	RTC->MODE0.CTRL.reg = 0x0;
	//RTC->MODE0.CTRL.reg |= RTC_MODE0_CTRL_MATCHCLR;
	RTC->MODE0.INTENSET.reg |= RTC_MODE0_INTENSET_CMP(8);
	//RTC->MODE0.EVCTRL.reg |= RTC_MODE0_EVCTRL_CMPEO(48);
	RTC->MODE0.CTRL.reg |= RTC_MODE0_CTRL_ENABLE;
	
}
void delay_us(int num){
	for(int i = num; i>0; i--){
		RTC->MODE0.COMP->reg=0;
		RTC->MODE0.INTFLAG.reg = RTC_MODE0_INTFLAG_CMP(8);
		while(!RTC->MODE0.INTFLAG.reg && RTC_MODE0_INTFLAG_CMP(8));
	}
	
}


#endif /* TIMING_H_ */